# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firstName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='lastName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
