# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_auto_20160802_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='takeHomePay',
        ),
    ]
